# Generated by Django 4.1.7 on 2023-02-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0004_remove_scope_project_scope_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='direct_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='indirect_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='labor',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='material',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='ocm_prcnt',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='profit_prcnt',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='profite_other_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='total_cost_no_vat',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='total_cost_w_vat',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='total_prcnt',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='vat_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='project',
        ),
        migrations.CreateModel(
            name='ScopeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit', models.CharField(default='lot', max_length=20)),
                ('material', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('labor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('equipment', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('direct_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ocm_prcnt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('profit_prcnt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_prcnt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('profite_other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vat_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('indirect_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cost_no_vat', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cost_w_vat', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='estimate.scope')),
            ],
        ),
        migrations.AddField(
            model_name='scope',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='scopes', to='estimate.project'),
        ),
    ]
