# Generated by Django 4.1.7 on 2023-02-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0009_itemtype_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('labor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('equipment', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_costs', to='estimate.division')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_costs', to='estimate.project')),
            ],
        ),
    ]
