# Generated by Django 4.1.7 on 2023-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0010_divisioncost'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisioncost',
            name='direct_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
