# Generated by Django 4.1.7 on 2023-02-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0014_project_direct_cost_project_equipment_project_labor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisioncost',
            name='direct_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='direct_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='direct_cost',
        ),
    ]
