# Generated by Django 4.1.7 on 2023-02-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0016_project_ocm_project_profit_project_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='indirect_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='ocm_prcnt',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='profit_other_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='profit_prcnt',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='total_cost_no_vat',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='total_cost_w_vat',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='total_prcnt',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='vat_cost',
        ),
    ]
