# Generated by Django 4.1.5 on 2023-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0017_remove_scope_indirect_cost_remove_scope_ocm_prcnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.CharField(blank=True, default='on-going', max_length=20, null=True),
        ),
    ]
