# Generated by Django 4.1.5 on 2023-03-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0018_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reject_msg',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
